class GaiaSource
  include Cequel::Record

  key :solution_id, :text
  key :source_id, :text
  key :random_index, :text
  column :ref_epoch, :text
  column :ra, :text
  column :ra_error, :text
  column :dec, :text
  column :dec_error, :text
  column :parallax, :text
  column :parallax_error, :text
  column :pmra, :text
  column :pmra_error, :text
  column :pmdec, :text
  column :pmdec_error, :text
  column :ra_dec_corr, :text
  column :ra_parallax_corr, :text
  column :ra_pmra_corr, :text
  column :ra_pmdec_corr, :text
  column :dec_parallax_corr, :text
  column :dec_pmra_corr, :text
  column :dec_pmdec_corr, :text
  column :parallax_pmra_corr, :text
  column :parallax_pmdec_corr, :text
  column :pmra_pmdec_corr, :text
  column :astrometric_n_obs_al, :text
  column :astrometric_n_obs_ac, :text
  column :astrometric_n_good_obs_al, :text
  column :astrometric_n_good_obs_ac, :text
  column :astrometric_n_bad_obs_al, :text
  column :astrometric_n_bad_obs_ac, :text
  column :astrometric_delta_q, :text
  column :astrometric_excess_noise, :text
  column :astrometric_excess_noise_sig, :text
  column :astrometric_primary_flag, :text
  column :astrometric_relegation_factor, :text
  column :astrometric_weight_al, :text
  column :astrometric_weight_ac, :text
  column :astrometric_priors_used, :text
  column :matched_observations, :text
  column :duplicated_source, :text
  column :scan_direction_strength_k1, :text
  column :scan_direction_strength_k2, :text
  column :scan_direction_strength_k3, :text
  column :scan_direction_strength_k4, :text
  column :scan_direction_mean_k1, :text
  column :scan_direction_mean_k2, :text
  column :scan_direction_mean_k3, :text
  column :scan_direction_mean_k4, :text
  column :phot_g_n_obs, :text
  column :phot_g_mean_flux, :text
  column :phot_g_mean_flux_error, :text
  column :phot_g_mean_mag, :text
  column :phot_variable_flag, :text
  column :l, :text
  column :b, :text
  column :ecl_lon, :text
  column :ecl_lat, :text
  timestamps
end
